name: Push it to the moon we goo!!!!!!
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every hour 
    - cron: "0 * * * *" 
  # push:
  #   branches:
  #     - main

env:
  AT_KEY: ${{ secrets.AT_KEY }}

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout hacky private tools
        uses: actions/checkout@v3
        with:
          repository: MinhPhu0304/at-dumper
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: at-dumper

      - name: Run all the things
        run: |
          cd at-dumper
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          go run main.go -file=../at-roadworks.json
          cd ../
          rm -rf at-dumper
          git status
          COMMIT_COUNT=$(git rev-list HEAD...origin/main --count)
          if [ -z "$(git diff HEAD^ HEAD)" ]; then
            echo "No new changes found."
            exit 0
          else

            git add at-roadworks.json
            git commit -m "Update at roadworks.json"
            git push origin main
          fi
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
          AT_KEY: ${{ secrets.AT_KEY }}
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

